services:
  - type: web
    name: minecraft-monitor
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      - key: PORT
        value: "10000"

      - key: DATABASE_URL
        fromDatabase:
          name: minecraft-monitor-db
          property: connectionString

      - key: JWT_SECRET
        generateValue: true

      - key: APP_USERNAME
        value: admin

      - key: APP_PASSWORD
        generateValue: true

      - key: CORS_ALLOWED_ORIGINS
        value: https://SEU-PROJETO.vercel.app

databases:
  - name: minecraft-monitor-db
    plan: free
    databaseName: minecraft_monitor
    user: minecraft