spring.application.name=minecraft-monitor
spring.datasource.url=jdbc:postgresql://localhost:5432/minecraft_monitor
spring.datasource.username=postgres
spring.datasource.password=*cw52[=?

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true