spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never

server.port=${PORT:10000}
server.address=0.0.0.0